# spring security \uAE30\uBCF8\uACC4\uC815 \uC124\uC815 (\uB9E4\uBC88 \uB2EC\uB77C\uC9C4 \uBE44\uBC88 \uCE58\uB294 \uBD88\uD3B8\uD568 \uC81C\uAC70)
spring:
  security:
    user:
      name: user
      password: 1111
